site_name: automation - OR - Back-end
plugins:
  - techdocs-core
nav:
  - Visão geral: index.md
  - Arquitetura: arquitetura.md
  - Ingestão de dados: ingestao.md
  - Motor de adequação: adequacao.md
  - API / Endpoints: api.md
  - Comunicações: comunicacoes.md
  - Realtime: realtime.md
