"""adiciona auth_users.auth_provider e libera password_hash nulo para SSO Microsoft

Revision ID: 031
Revises: 030
Create Date: 2026-08-20 11:37:04.262118

Contas autenticadas via Microsoft Entra ID (feat/auth-microsoft-sso) não têm
senha local — `password_hash` passa a aceitar nulo e `auth_provider` marca a
origem da conta (`local` por padrão via `server_default`, preservando as
linhas existentes; `microsoft` para as provisionadas pelo SSO).
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "031"
down_revision: str | None = "030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_users",
        sa.Column(
            "auth_provider",
            sa.String(length=20),
            server_default="local",
            nullable=False,
        ),
    )
    op.alter_column(
        "auth_users",
        "password_hash",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_users",
        "password_hash",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("auth_users", "auth_provider")
    # ### end Alembic commands ###
